# Default target to build both server and client
all: server client

# Compile server
server:
	gcc server.c -o server

# Compile client
client:
	gcc client.c -o client

# Clean up build files
clean:
	rm -f server client